FROM alpine:latest

ENV TZ=Asia/Shanghai \
    LANG=C.UTF-8

VOLUME /etc/sillyGirl

RUN mkdir /usr/local/sillyGirl && cd /usr/local/sillyGirl \
    && wget https://raw.githubusercontent.com/callacat/Docker-sillyGirl/main/file/sillyGirl_amd_220807 \
    && mv sillyGirl_amd_220807 sillyGirl && chmod 777 sillyGirl \
    && mkdir /lib64 && ln -s /lib/libc.musl-x86_64.so.1 /lib64/ld-linux-x86-64.so.2 \
    && apk add --no-cache tzdata && cp /usr/share/zoneinfo/$TZ /etc/localtime

CMD ["/usr/local/sillyGirl/sillyGirl", "-t"]