FROM alpine:latest

ENV TZ=Asia/Shanghai \
    LANG=C.UTF-8

VOLUME /etc/sillyGirl

RUN mkdir /usr/local/sillyGirl && cd /usr/local/sillyGirl \
    && wget https://raw.githubusercontent.com/callacat/Docker-sillyGirl/main/file/sillyGirl_arm_220914 \
    && mv sillyGirl_arm_220914 sillyGirl && chmod 777 sillyGirl \
    && apk add --no-cache tzdata && cp /usr/share/zoneinfo/$TZ /etc/localtime
    
CMD ["/usr/local/sillyGirl/sillyGirl", "-t"]