FROM alpine:latest

ENV LANG=C.UTF-8

COPY monitor.sh /usr/local/bin/monitor.sh

RUN chmod +x /usr/local/bin/monitor.sh \
    && mkdir /usr/local/sillyGirl && cd /usr/local/sillyGirl \
    && wget https://github.com/cdle/sillyGirl/releases/download/main/sillyGirl_linux_arm64 \
    && mv sillyGirl_linux_arm64 sillyGirl && chmod 777 sillyGirl \
    && apk add --no-cache tzdata procps && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

ENTRYPOINT ["/usr/local/bin/monitor.sh"]