FROM alpine:latest

ENV TZ=Asia/Shanghai \
    LANG=C.UTF-8

VOLUME /etc/sillyplus

RUN mkdir /usr/local/sillyGirl && cd /usr/local/sillyGirl \
    && wget https://github.com/cdle/sillyGirl/releases/download/main/sillyGirl_linux_arm64 \
    && mv sillyGirl_linux_arm64 sillyGirl && chmod 777 sillyGirl \
    && apk add --no-cache tzdata && cp /usr/share/zoneinfo/$TZ /etc/localtime
    
CMD ["/usr/local/sillyGirl/sillyGirl", "-t"]